// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface AddStarReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.AddStarReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tarekomi_id = 1;</code>
   */
  long getTarekomiId();
}
