// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

/**
 * Protobuf type {@code evileye.AddStarReq}
 */
public  final class AddStarReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:evileye.AddStarReq)
    AddStarReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddStarReq.newBuilder() to construct.
  private AddStarReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddStarReq() {
    tarekomiId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddStarReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            tarekomiId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_AddStarReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_AddStarReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yt8492.evileye.protobuf.AddStarReq.class, com.yt8492.evileye.protobuf.AddStarReq.Builder.class);
  }

  public static final int TAREKOMI_ID_FIELD_NUMBER = 1;
  private long tarekomiId_;
  /**
   * <code>int64 tarekomi_id = 1;</code>
   */
  public long getTarekomiId() {
    return tarekomiId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tarekomiId_ != 0L) {
      output.writeInt64(1, tarekomiId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tarekomiId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, tarekomiId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yt8492.evileye.protobuf.AddStarReq)) {
      return super.equals(obj);
    }
    com.yt8492.evileye.protobuf.AddStarReq other = (com.yt8492.evileye.protobuf.AddStarReq) obj;

    boolean result = true;
    result = result && (getTarekomiId()
        == other.getTarekomiId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TAREKOMI_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTarekomiId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.AddStarReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yt8492.evileye.protobuf.AddStarReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code evileye.AddStarReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:evileye.AddStarReq)
      com.yt8492.evileye.protobuf.AddStarReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_AddStarReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_AddStarReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yt8492.evileye.protobuf.AddStarReq.class, com.yt8492.evileye.protobuf.AddStarReq.Builder.class);
    }

    // Construct using com.yt8492.evileye.protobuf.AddStarReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tarekomiId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_AddStarReq_descriptor;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.AddStarReq getDefaultInstanceForType() {
      return com.yt8492.evileye.protobuf.AddStarReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.AddStarReq build() {
      com.yt8492.evileye.protobuf.AddStarReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.AddStarReq buildPartial() {
      com.yt8492.evileye.protobuf.AddStarReq result = new com.yt8492.evileye.protobuf.AddStarReq(this);
      result.tarekomiId_ = tarekomiId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yt8492.evileye.protobuf.AddStarReq) {
        return mergeFrom((com.yt8492.evileye.protobuf.AddStarReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yt8492.evileye.protobuf.AddStarReq other) {
      if (other == com.yt8492.evileye.protobuf.AddStarReq.getDefaultInstance()) return this;
      if (other.getTarekomiId() != 0L) {
        setTarekomiId(other.getTarekomiId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yt8492.evileye.protobuf.AddStarReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yt8492.evileye.protobuf.AddStarReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long tarekomiId_ ;
    /**
     * <code>int64 tarekomi_id = 1;</code>
     */
    public long getTarekomiId() {
      return tarekomiId_;
    }
    /**
     * <code>int64 tarekomi_id = 1;</code>
     */
    public Builder setTarekomiId(long value) {
      
      tarekomiId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tarekomi_id = 1;</code>
     */
    public Builder clearTarekomiId() {
      
      tarekomiId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:evileye.AddStarReq)
  }

  // @@protoc_insertion_point(class_scope:evileye.AddStarReq)
  private static final com.yt8492.evileye.protobuf.AddStarReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yt8492.evileye.protobuf.AddStarReq();
  }

  public static com.yt8492.evileye.protobuf.AddStarReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddStarReq>
      PARSER = new com.google.protobuf.AbstractParser<AddStarReq>() {
    @java.lang.Override
    public AddStarReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddStarReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddStarReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddStarReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yt8492.evileye.protobuf.AddStarReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

