// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public final class EeProto {
  private EeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_Tarekomi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_Tarekomi_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_HealthCheckRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_HealthCheckRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_TarekomiReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_TarekomiReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_VoteReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_VoteReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_TarekomiBoardReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_TarekomiBoardReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_TarekomiSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_TarekomiSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_TarekomiSummaries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_TarekomiSummaries_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_TarekomiBoardRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_TarekomiBoardRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_UserInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_UserInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_GetUserListReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_GetUserListReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_Users_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_Users_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evileye_AddStarReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evileye_AddStarReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022protobuf/api.proto\022\007evileye\032\033google/pr" +
      "otobuf/empty.proto\"=\n\010Tarekomi\022\026\n\016target" +
      "_user_id\030\001 \001(\003\022\013\n\003url\030\003 \001(\t\022\014\n\004desc\030\004 \001(" +
      "\t\"P\n\004User\022\017\n\007user_id\030\001 \001(\003\022\021\n\tuser_name\030" +
      "\002 \001(\t\022$\n\ttarekomis\030\003 \003(\0132\021.evileye.Tarek" +
      "omi\"9\n\016HealthCheckRes\022\023\n\013commit_hash\030\001 \001" +
      "(\t\022\022\n\nbuild_time\030\002 \001(\004\"2\n\013TarekomiReq\022#\n" +
      "\010tarekomi\030\001 \001(\0132\021.evileye.Tarekomi\",\n\007Vo" +
      "teReq\022\023\n\013tarekomi_id\030\001 \001(\003\022\014\n\004desc\030\002 \001(\t" +
      "\"1\n\020TarekomiBoardReq\022\r\n\005limit\030\001 \001(\003\022\016\n\006o" +
      "ffset\030\002 \001(\003\"I\n\017TarekomiSummary\022#\n\010tareko" +
      "mi\030\001 \001(\0132\021.evileye.Tarekomi\022\021\n\tuser_name" +
      "\030\002 \001(\t\"@\n\021TarekomiSummaries\022+\n\ttarekomis" +
      "\030\001 \003(\0132\030.evileye.TarekomiSummary\"?\n\020Tare" +
      "komiBoardRes\022+\n\ttarekomis\030\001 \003(\0132\030.eviley" +
      "e.TarekomiSummary\" \n\013UserInfoReq\022\021\n\tuser" +
      "_name\030\001 \001(\003\"/\n\016GetUserListReq\022\r\n\005limit\030\001" +
      " \001(\003\022\016\n\006offset\030\002 \001(\003\"%\n\005Users\022\034\n\005users\030\001" +
      " \003(\0132\r.evileye.User\"!\n\nAddStarReq\022\023\n\013tar" +
      "ekomi_id\030\001 \001(\0032\351\003\n\007Private\022>\n\013HealthChec" +
      "k\022\026.google.protobuf.Empty\032\027.evileye.Heal" +
      "thCheckRes\0228\n\010Tarekomi\022\024.evileye.Tarekom" +
      "iReq\032\026.google.protobuf.Empty\0220\n\004Vote\022\020.e" +
      "vileye.VoteReq\032\026.google.protobuf.Empty\022E" +
      "\n\rTarekomiBoard\022\031.evileye.TarekomiBoardR" +
      "eq\032\031.evileye.TarekomiBoardRes\0222\n\013GetUser" +
      "Info\022\024.evileye.UserInfoReq\032\r.evileye.Use" +
      "r\0226\n\013GetUserList\022\027.evileye.GetUserListRe" +
      "q\032\016.evileye.Users\0226\n\007AddStar\022\023.evileye.A" +
      "ddStarReq\032\026.google.protobuf.Empty\022G\n\021Get" +
      "StaredTarekomi\022\026.google.protobuf.Empty\032\032" +
      ".evileye.TarekomiSummariesB(\n\033com.yt8492" +
      ".evileye.protobufB\007EeProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_evileye_Tarekomi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_evileye_Tarekomi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_Tarekomi_descriptor,
        new java.lang.String[] { "TargetUserId", "Url", "Desc", });
    internal_static_evileye_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_evileye_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_User_descriptor,
        new java.lang.String[] { "UserId", "UserName", "Tarekomis", });
    internal_static_evileye_HealthCheckRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_evileye_HealthCheckRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_HealthCheckRes_descriptor,
        new java.lang.String[] { "CommitHash", "BuildTime", });
    internal_static_evileye_TarekomiReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_evileye_TarekomiReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_TarekomiReq_descriptor,
        new java.lang.String[] { "Tarekomi", });
    internal_static_evileye_VoteReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_evileye_VoteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_VoteReq_descriptor,
        new java.lang.String[] { "TarekomiId", "Desc", });
    internal_static_evileye_TarekomiBoardReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_evileye_TarekomiBoardReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_TarekomiBoardReq_descriptor,
        new java.lang.String[] { "Limit", "Offset", });
    internal_static_evileye_TarekomiSummary_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_evileye_TarekomiSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_TarekomiSummary_descriptor,
        new java.lang.String[] { "Tarekomi", "UserName", });
    internal_static_evileye_TarekomiSummaries_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_evileye_TarekomiSummaries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_TarekomiSummaries_descriptor,
        new java.lang.String[] { "Tarekomis", });
    internal_static_evileye_TarekomiBoardRes_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_evileye_TarekomiBoardRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_TarekomiBoardRes_descriptor,
        new java.lang.String[] { "Tarekomis", });
    internal_static_evileye_UserInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_evileye_UserInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_UserInfoReq_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_evileye_GetUserListReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_evileye_GetUserListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_GetUserListReq_descriptor,
        new java.lang.String[] { "Limit", "Offset", });
    internal_static_evileye_Users_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_evileye_Users_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_Users_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_evileye_AddStarReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_evileye_AddStarReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evileye_AddStarReq_descriptor,
        new java.lang.String[] { "TarekomiId", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
