// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

/**
 * Protobuf type {@code evileye.HealthCheckRes}
 */
public  final class HealthCheckRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:evileye.HealthCheckRes)
    HealthCheckResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HealthCheckRes.newBuilder() to construct.
  private HealthCheckRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HealthCheckRes() {
    commitHash_ = "";
    buildTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HealthCheckRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            commitHash_ = s;
            break;
          }
          case 16: {

            buildTime_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_HealthCheckRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_HealthCheckRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yt8492.evileye.protobuf.HealthCheckRes.class, com.yt8492.evileye.protobuf.HealthCheckRes.Builder.class);
  }

  public static final int COMMIT_HASH_FIELD_NUMBER = 1;
  private volatile java.lang.Object commitHash_;
  /**
   * <code>string commit_hash = 1;</code>
   */
  public java.lang.String getCommitHash() {
    java.lang.Object ref = commitHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commitHash_ = s;
      return s;
    }
  }
  /**
   * <code>string commit_hash = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCommitHashBytes() {
    java.lang.Object ref = commitHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commitHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUILD_TIME_FIELD_NUMBER = 2;
  private long buildTime_;
  /**
   * <code>uint64 build_time = 2;</code>
   */
  public long getBuildTime() {
    return buildTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCommitHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commitHash_);
    }
    if (buildTime_ != 0L) {
      output.writeUInt64(2, buildTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCommitHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commitHash_);
    }
    if (buildTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, buildTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yt8492.evileye.protobuf.HealthCheckRes)) {
      return super.equals(obj);
    }
    com.yt8492.evileye.protobuf.HealthCheckRes other = (com.yt8492.evileye.protobuf.HealthCheckRes) obj;

    boolean result = true;
    result = result && getCommitHash()
        .equals(other.getCommitHash());
    result = result && (getBuildTime()
        == other.getBuildTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMIT_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getCommitHash().hashCode();
    hash = (37 * hash) + BUILD_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBuildTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.HealthCheckRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yt8492.evileye.protobuf.HealthCheckRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code evileye.HealthCheckRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:evileye.HealthCheckRes)
      com.yt8492.evileye.protobuf.HealthCheckResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_HealthCheckRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_HealthCheckRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yt8492.evileye.protobuf.HealthCheckRes.class, com.yt8492.evileye.protobuf.HealthCheckRes.Builder.class);
    }

    // Construct using com.yt8492.evileye.protobuf.HealthCheckRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      commitHash_ = "";

      buildTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_HealthCheckRes_descriptor;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.HealthCheckRes getDefaultInstanceForType() {
      return com.yt8492.evileye.protobuf.HealthCheckRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.HealthCheckRes build() {
      com.yt8492.evileye.protobuf.HealthCheckRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.HealthCheckRes buildPartial() {
      com.yt8492.evileye.protobuf.HealthCheckRes result = new com.yt8492.evileye.protobuf.HealthCheckRes(this);
      result.commitHash_ = commitHash_;
      result.buildTime_ = buildTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yt8492.evileye.protobuf.HealthCheckRes) {
        return mergeFrom((com.yt8492.evileye.protobuf.HealthCheckRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yt8492.evileye.protobuf.HealthCheckRes other) {
      if (other == com.yt8492.evileye.protobuf.HealthCheckRes.getDefaultInstance()) return this;
      if (!other.getCommitHash().isEmpty()) {
        commitHash_ = other.commitHash_;
        onChanged();
      }
      if (other.getBuildTime() != 0L) {
        setBuildTime(other.getBuildTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yt8492.evileye.protobuf.HealthCheckRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yt8492.evileye.protobuf.HealthCheckRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object commitHash_ = "";
    /**
     * <code>string commit_hash = 1;</code>
     */
    public java.lang.String getCommitHash() {
      java.lang.Object ref = commitHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commit_hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommitHashBytes() {
      java.lang.Object ref = commitHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commit_hash = 1;</code>
     */
    public Builder setCommitHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commitHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string commit_hash = 1;</code>
     */
    public Builder clearCommitHash() {
      
      commitHash_ = getDefaultInstance().getCommitHash();
      onChanged();
      return this;
    }
    /**
     * <code>string commit_hash = 1;</code>
     */
    public Builder setCommitHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commitHash_ = value;
      onChanged();
      return this;
    }

    private long buildTime_ ;
    /**
     * <code>uint64 build_time = 2;</code>
     */
    public long getBuildTime() {
      return buildTime_;
    }
    /**
     * <code>uint64 build_time = 2;</code>
     */
    public Builder setBuildTime(long value) {
      
      buildTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 build_time = 2;</code>
     */
    public Builder clearBuildTime() {
      
      buildTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:evileye.HealthCheckRes)
  }

  // @@protoc_insertion_point(class_scope:evileye.HealthCheckRes)
  private static final com.yt8492.evileye.protobuf.HealthCheckRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yt8492.evileye.protobuf.HealthCheckRes();
  }

  public static com.yt8492.evileye.protobuf.HealthCheckRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HealthCheckRes>
      PARSER = new com.google.protobuf.AbstractParser<HealthCheckRes>() {
    @java.lang.Override
    public HealthCheckRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HealthCheckRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HealthCheckRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HealthCheckRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yt8492.evileye.protobuf.HealthCheckRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

