// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface HealthCheckResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.HealthCheckRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commit_hash = 1;</code>
   */
  java.lang.String getCommitHash();
  /**
   * <code>string commit_hash = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommitHashBytes();

  /**
   * <code>uint64 build_time = 2;</code>
   */
  long getBuildTime();
}
