// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface TarekomiBoardReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.TarekomiBoardReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 limit = 1;</code>
   */
  long getLimit();

  /**
   * <code>int64 offset = 2;</code>
   */
  long getOffset();
}
