// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface TarekomiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.Tarekomi)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 target_user_id = 1;</code>
   */
  long getTargetUserId();

  /**
   * <code>string url = 3;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string desc = 4;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
