// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

/**
 * Protobuf type {@code evileye.TarekomiReq}
 */
public  final class TarekomiReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:evileye.TarekomiReq)
    TarekomiReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TarekomiReq.newBuilder() to construct.
  private TarekomiReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TarekomiReq() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TarekomiReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.yt8492.evileye.protobuf.Tarekomi.Builder subBuilder = null;
            if (tarekomi_ != null) {
              subBuilder = tarekomi_.toBuilder();
            }
            tarekomi_ = input.readMessage(com.yt8492.evileye.protobuf.Tarekomi.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tarekomi_);
              tarekomi_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yt8492.evileye.protobuf.TarekomiReq.class, com.yt8492.evileye.protobuf.TarekomiReq.Builder.class);
  }

  public static final int TAREKOMI_FIELD_NUMBER = 1;
  private com.yt8492.evileye.protobuf.Tarekomi tarekomi_;
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  public boolean hasTarekomi() {
    return tarekomi_ != null;
  }
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  public com.yt8492.evileye.protobuf.Tarekomi getTarekomi() {
    return tarekomi_ == null ? com.yt8492.evileye.protobuf.Tarekomi.getDefaultInstance() : tarekomi_;
  }
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  public com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomiOrBuilder() {
    return getTarekomi();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tarekomi_ != null) {
      output.writeMessage(1, getTarekomi());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tarekomi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTarekomi());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yt8492.evileye.protobuf.TarekomiReq)) {
      return super.equals(obj);
    }
    com.yt8492.evileye.protobuf.TarekomiReq other = (com.yt8492.evileye.protobuf.TarekomiReq) obj;

    boolean result = true;
    result = result && (hasTarekomi() == other.hasTarekomi());
    if (hasTarekomi()) {
      result = result && getTarekomi()
          .equals(other.getTarekomi());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTarekomi()) {
      hash = (37 * hash) + TAREKOMI_FIELD_NUMBER;
      hash = (53 * hash) + getTarekomi().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.TarekomiReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yt8492.evileye.protobuf.TarekomiReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code evileye.TarekomiReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:evileye.TarekomiReq)
      com.yt8492.evileye.protobuf.TarekomiReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yt8492.evileye.protobuf.TarekomiReq.class, com.yt8492.evileye.protobuf.TarekomiReq.Builder.class);
    }

    // Construct using com.yt8492.evileye.protobuf.TarekomiReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tarekomiBuilder_ == null) {
        tarekomi_ = null;
      } else {
        tarekomi_ = null;
        tarekomiBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiReq_descriptor;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.TarekomiReq getDefaultInstanceForType() {
      return com.yt8492.evileye.protobuf.TarekomiReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.TarekomiReq build() {
      com.yt8492.evileye.protobuf.TarekomiReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.TarekomiReq buildPartial() {
      com.yt8492.evileye.protobuf.TarekomiReq result = new com.yt8492.evileye.protobuf.TarekomiReq(this);
      if (tarekomiBuilder_ == null) {
        result.tarekomi_ = tarekomi_;
      } else {
        result.tarekomi_ = tarekomiBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yt8492.evileye.protobuf.TarekomiReq) {
        return mergeFrom((com.yt8492.evileye.protobuf.TarekomiReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yt8492.evileye.protobuf.TarekomiReq other) {
      if (other == com.yt8492.evileye.protobuf.TarekomiReq.getDefaultInstance()) return this;
      if (other.hasTarekomi()) {
        mergeTarekomi(other.getTarekomi());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yt8492.evileye.protobuf.TarekomiReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yt8492.evileye.protobuf.TarekomiReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.yt8492.evileye.protobuf.Tarekomi tarekomi_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.yt8492.evileye.protobuf.Tarekomi, com.yt8492.evileye.protobuf.Tarekomi.Builder, com.yt8492.evileye.protobuf.TarekomiOrBuilder> tarekomiBuilder_;
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public boolean hasTarekomi() {
      return tarekomiBuilder_ != null || tarekomi_ != null;
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public com.yt8492.evileye.protobuf.Tarekomi getTarekomi() {
      if (tarekomiBuilder_ == null) {
        return tarekomi_ == null ? com.yt8492.evileye.protobuf.Tarekomi.getDefaultInstance() : tarekomi_;
      } else {
        return tarekomiBuilder_.getMessage();
      }
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public Builder setTarekomi(com.yt8492.evileye.protobuf.Tarekomi value) {
      if (tarekomiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tarekomi_ = value;
        onChanged();
      } else {
        tarekomiBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public Builder setTarekomi(
        com.yt8492.evileye.protobuf.Tarekomi.Builder builderForValue) {
      if (tarekomiBuilder_ == null) {
        tarekomi_ = builderForValue.build();
        onChanged();
      } else {
        tarekomiBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public Builder mergeTarekomi(com.yt8492.evileye.protobuf.Tarekomi value) {
      if (tarekomiBuilder_ == null) {
        if (tarekomi_ != null) {
          tarekomi_ =
            com.yt8492.evileye.protobuf.Tarekomi.newBuilder(tarekomi_).mergeFrom(value).buildPartial();
        } else {
          tarekomi_ = value;
        }
        onChanged();
      } else {
        tarekomiBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public Builder clearTarekomi() {
      if (tarekomiBuilder_ == null) {
        tarekomi_ = null;
        onChanged();
      } else {
        tarekomi_ = null;
        tarekomiBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public com.yt8492.evileye.protobuf.Tarekomi.Builder getTarekomiBuilder() {
      
      onChanged();
      return getTarekomiFieldBuilder().getBuilder();
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomiOrBuilder() {
      if (tarekomiBuilder_ != null) {
        return tarekomiBuilder_.getMessageOrBuilder();
      } else {
        return tarekomi_ == null ?
            com.yt8492.evileye.protobuf.Tarekomi.getDefaultInstance() : tarekomi_;
      }
    }
    /**
     * <code>.evileye.Tarekomi tarekomi = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.yt8492.evileye.protobuf.Tarekomi, com.yt8492.evileye.protobuf.Tarekomi.Builder, com.yt8492.evileye.protobuf.TarekomiOrBuilder> 
        getTarekomiFieldBuilder() {
      if (tarekomiBuilder_ == null) {
        tarekomiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.yt8492.evileye.protobuf.Tarekomi, com.yt8492.evileye.protobuf.Tarekomi.Builder, com.yt8492.evileye.protobuf.TarekomiOrBuilder>(
                getTarekomi(),
                getParentForChildren(),
                isClean());
        tarekomi_ = null;
      }
      return tarekomiBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:evileye.TarekomiReq)
  }

  // @@protoc_insertion_point(class_scope:evileye.TarekomiReq)
  private static final com.yt8492.evileye.protobuf.TarekomiReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yt8492.evileye.protobuf.TarekomiReq();
  }

  public static com.yt8492.evileye.protobuf.TarekomiReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TarekomiReq>
      PARSER = new com.google.protobuf.AbstractParser<TarekomiReq>() {
    @java.lang.Override
    public TarekomiReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TarekomiReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TarekomiReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TarekomiReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yt8492.evileye.protobuf.TarekomiReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

