// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

/**
 * Protobuf type {@code evileye.TarekomiBoardRes}
 */
public  final class TarekomiBoardRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:evileye.TarekomiBoardRes)
    TarekomiBoardResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TarekomiBoardRes.newBuilder() to construct.
  private TarekomiBoardRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TarekomiBoardRes() {
    tarekomis_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TarekomiBoardRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tarekomis_ = new java.util.ArrayList<com.yt8492.evileye.protobuf.TarekomiSummary>();
              mutable_bitField0_ |= 0x00000001;
            }
            tarekomis_.add(
                input.readMessage(com.yt8492.evileye.protobuf.TarekomiSummary.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tarekomis_ = java.util.Collections.unmodifiableList(tarekomis_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiBoardRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiBoardRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yt8492.evileye.protobuf.TarekomiBoardRes.class, com.yt8492.evileye.protobuf.TarekomiBoardRes.Builder.class);
  }

  public static final int TAREKOMIS_FIELD_NUMBER = 1;
  private java.util.List<com.yt8492.evileye.protobuf.TarekomiSummary> tarekomis_;
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  public java.util.List<com.yt8492.evileye.protobuf.TarekomiSummary> getTarekomisList() {
    return tarekomis_;
  }
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  public java.util.List<? extends com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder> 
      getTarekomisOrBuilderList() {
    return tarekomis_;
  }
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  public int getTarekomisCount() {
    return tarekomis_.size();
  }
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  public com.yt8492.evileye.protobuf.TarekomiSummary getTarekomis(int index) {
    return tarekomis_.get(index);
  }
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  public com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder getTarekomisOrBuilder(
      int index) {
    return tarekomis_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tarekomis_.size(); i++) {
      output.writeMessage(1, tarekomis_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tarekomis_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tarekomis_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yt8492.evileye.protobuf.TarekomiBoardRes)) {
      return super.equals(obj);
    }
    com.yt8492.evileye.protobuf.TarekomiBoardRes other = (com.yt8492.evileye.protobuf.TarekomiBoardRes) obj;

    boolean result = true;
    result = result && getTarekomisList()
        .equals(other.getTarekomisList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTarekomisCount() > 0) {
      hash = (37 * hash) + TAREKOMIS_FIELD_NUMBER;
      hash = (53 * hash) + getTarekomisList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.TarekomiBoardRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yt8492.evileye.protobuf.TarekomiBoardRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code evileye.TarekomiBoardRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:evileye.TarekomiBoardRes)
      com.yt8492.evileye.protobuf.TarekomiBoardResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiBoardRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiBoardRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yt8492.evileye.protobuf.TarekomiBoardRes.class, com.yt8492.evileye.protobuf.TarekomiBoardRes.Builder.class);
    }

    // Construct using com.yt8492.evileye.protobuf.TarekomiBoardRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTarekomisFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tarekomisBuilder_ == null) {
        tarekomis_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tarekomisBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_TarekomiBoardRes_descriptor;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.TarekomiBoardRes getDefaultInstanceForType() {
      return com.yt8492.evileye.protobuf.TarekomiBoardRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.TarekomiBoardRes build() {
      com.yt8492.evileye.protobuf.TarekomiBoardRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.TarekomiBoardRes buildPartial() {
      com.yt8492.evileye.protobuf.TarekomiBoardRes result = new com.yt8492.evileye.protobuf.TarekomiBoardRes(this);
      int from_bitField0_ = bitField0_;
      if (tarekomisBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tarekomis_ = java.util.Collections.unmodifiableList(tarekomis_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tarekomis_ = tarekomis_;
      } else {
        result.tarekomis_ = tarekomisBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yt8492.evileye.protobuf.TarekomiBoardRes) {
        return mergeFrom((com.yt8492.evileye.protobuf.TarekomiBoardRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yt8492.evileye.protobuf.TarekomiBoardRes other) {
      if (other == com.yt8492.evileye.protobuf.TarekomiBoardRes.getDefaultInstance()) return this;
      if (tarekomisBuilder_ == null) {
        if (!other.tarekomis_.isEmpty()) {
          if (tarekomis_.isEmpty()) {
            tarekomis_ = other.tarekomis_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTarekomisIsMutable();
            tarekomis_.addAll(other.tarekomis_);
          }
          onChanged();
        }
      } else {
        if (!other.tarekomis_.isEmpty()) {
          if (tarekomisBuilder_.isEmpty()) {
            tarekomisBuilder_.dispose();
            tarekomisBuilder_ = null;
            tarekomis_ = other.tarekomis_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tarekomisBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTarekomisFieldBuilder() : null;
          } else {
            tarekomisBuilder_.addAllMessages(other.tarekomis_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yt8492.evileye.protobuf.TarekomiBoardRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yt8492.evileye.protobuf.TarekomiBoardRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.yt8492.evileye.protobuf.TarekomiSummary> tarekomis_ =
      java.util.Collections.emptyList();
    private void ensureTarekomisIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tarekomis_ = new java.util.ArrayList<com.yt8492.evileye.protobuf.TarekomiSummary>(tarekomis_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yt8492.evileye.protobuf.TarekomiSummary, com.yt8492.evileye.protobuf.TarekomiSummary.Builder, com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder> tarekomisBuilder_;

    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public java.util.List<com.yt8492.evileye.protobuf.TarekomiSummary> getTarekomisList() {
      if (tarekomisBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tarekomis_);
      } else {
        return tarekomisBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public int getTarekomisCount() {
      if (tarekomisBuilder_ == null) {
        return tarekomis_.size();
      } else {
        return tarekomisBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiSummary getTarekomis(int index) {
      if (tarekomisBuilder_ == null) {
        return tarekomis_.get(index);
      } else {
        return tarekomisBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder setTarekomis(
        int index, com.yt8492.evileye.protobuf.TarekomiSummary value) {
      if (tarekomisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTarekomisIsMutable();
        tarekomis_.set(index, value);
        onChanged();
      } else {
        tarekomisBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder setTarekomis(
        int index, com.yt8492.evileye.protobuf.TarekomiSummary.Builder builderForValue) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.set(index, builderForValue.build());
        onChanged();
      } else {
        tarekomisBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder addTarekomis(com.yt8492.evileye.protobuf.TarekomiSummary value) {
      if (tarekomisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTarekomisIsMutable();
        tarekomis_.add(value);
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder addTarekomis(
        int index, com.yt8492.evileye.protobuf.TarekomiSummary value) {
      if (tarekomisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTarekomisIsMutable();
        tarekomis_.add(index, value);
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder addTarekomis(
        com.yt8492.evileye.protobuf.TarekomiSummary.Builder builderForValue) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.add(builderForValue.build());
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder addTarekomis(
        int index, com.yt8492.evileye.protobuf.TarekomiSummary.Builder builderForValue) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.add(index, builderForValue.build());
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder addAllTarekomis(
        java.lang.Iterable<? extends com.yt8492.evileye.protobuf.TarekomiSummary> values) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tarekomis_);
        onChanged();
      } else {
        tarekomisBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder clearTarekomis() {
      if (tarekomisBuilder_ == null) {
        tarekomis_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tarekomisBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public Builder removeTarekomis(int index) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.remove(index);
        onChanged();
      } else {
        tarekomisBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiSummary.Builder getTarekomisBuilder(
        int index) {
      return getTarekomisFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder getTarekomisOrBuilder(
        int index) {
      if (tarekomisBuilder_ == null) {
        return tarekomis_.get(index);  } else {
        return tarekomisBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public java.util.List<? extends com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder> 
         getTarekomisOrBuilderList() {
      if (tarekomisBuilder_ != null) {
        return tarekomisBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tarekomis_);
      }
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiSummary.Builder addTarekomisBuilder() {
      return getTarekomisFieldBuilder().addBuilder(
          com.yt8492.evileye.protobuf.TarekomiSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiSummary.Builder addTarekomisBuilder(
        int index) {
      return getTarekomisFieldBuilder().addBuilder(
          index, com.yt8492.evileye.protobuf.TarekomiSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
     */
    public java.util.List<com.yt8492.evileye.protobuf.TarekomiSummary.Builder> 
         getTarekomisBuilderList() {
      return getTarekomisFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yt8492.evileye.protobuf.TarekomiSummary, com.yt8492.evileye.protobuf.TarekomiSummary.Builder, com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder> 
        getTarekomisFieldBuilder() {
      if (tarekomisBuilder_ == null) {
        tarekomisBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yt8492.evileye.protobuf.TarekomiSummary, com.yt8492.evileye.protobuf.TarekomiSummary.Builder, com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder>(
                tarekomis_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        tarekomis_ = null;
      }
      return tarekomisBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:evileye.TarekomiBoardRes)
  }

  // @@protoc_insertion_point(class_scope:evileye.TarekomiBoardRes)
  private static final com.yt8492.evileye.protobuf.TarekomiBoardRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yt8492.evileye.protobuf.TarekomiBoardRes();
  }

  public static com.yt8492.evileye.protobuf.TarekomiBoardRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TarekomiBoardRes>
      PARSER = new com.google.protobuf.AbstractParser<TarekomiBoardRes>() {
    @java.lang.Override
    public TarekomiBoardRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TarekomiBoardRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TarekomiBoardRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TarekomiBoardRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yt8492.evileye.protobuf.TarekomiBoardRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

