// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface TarekomiReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.TarekomiReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  boolean hasTarekomi();
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  com.yt8492.evileye.protobuf.Tarekomi getTarekomi();
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomiOrBuilder();
}
