// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface TarekomiSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.TarekomiSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  boolean hasTarekomi();
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  com.yt8492.evileye.protobuf.Tarekomi getTarekomi();
  /**
   * <code>.evileye.Tarekomi tarekomi = 1;</code>
   */
  com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomiOrBuilder();

  /**
   * <code>string user_name = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
