// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface TarekomiSummariesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.TarekomiSummaries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  java.util.List<com.yt8492.evileye.protobuf.TarekomiSummary> 
      getTarekomisList();
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  com.yt8492.evileye.protobuf.TarekomiSummary getTarekomis(int index);
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  int getTarekomisCount();
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  java.util.List<? extends com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder> 
      getTarekomisOrBuilderList();
  /**
   * <code>repeated .evileye.TarekomiSummary tarekomis = 1;</code>
   */
  com.yt8492.evileye.protobuf.TarekomiSummaryOrBuilder getTarekomisOrBuilder(
      int index);
}
