// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface UserInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.UserInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_name = 1;</code>
   */
  long getUserName();
}
