// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

/**
 * Protobuf type {@code evileye.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:evileye.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    userId_ = 0L;
    userName_ = "";
    tarekomis_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              tarekomis_ = new java.util.ArrayList<com.yt8492.evileye.protobuf.Tarekomi>();
              mutable_bitField0_ |= 0x00000004;
            }
            tarekomis_.add(
                input.readMessage(com.yt8492.evileye.protobuf.Tarekomi.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        tarekomis_ = java.util.Collections.unmodifiableList(tarekomis_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yt8492.evileye.protobuf.User.class, com.yt8492.evileye.protobuf.User.Builder.class);
  }

  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <code>int64 user_id = 1;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int USER_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object userName_;
  /**
   * <code>string user_name = 2;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string user_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAREKOMIS_FIELD_NUMBER = 3;
  private java.util.List<com.yt8492.evileye.protobuf.Tarekomi> tarekomis_;
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  public java.util.List<com.yt8492.evileye.protobuf.Tarekomi> getTarekomisList() {
    return tarekomis_;
  }
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  public java.util.List<? extends com.yt8492.evileye.protobuf.TarekomiOrBuilder> 
      getTarekomisOrBuilderList() {
    return tarekomis_;
  }
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  public int getTarekomisCount() {
    return tarekomis_.size();
  }
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  public com.yt8492.evileye.protobuf.Tarekomi getTarekomis(int index) {
    return tarekomis_.get(index);
  }
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  public com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomisOrBuilder(
      int index) {
    return tarekomis_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
    }
    for (int i = 0; i < tarekomis_.size(); i++) {
      output.writeMessage(3, tarekomis_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
    }
    for (int i = 0; i < tarekomis_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tarekomis_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yt8492.evileye.protobuf.User)) {
      return super.equals(obj);
    }
    com.yt8492.evileye.protobuf.User other = (com.yt8492.evileye.protobuf.User) obj;

    boolean result = true;
    result = result && (getUserId()
        == other.getUserId());
    result = result && getUserName()
        .equals(other.getUserName());
    result = result && getTarekomisList()
        .equals(other.getTarekomisList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    if (getTarekomisCount() > 0) {
      hash = (37 * hash) + TAREKOMIS_FIELD_NUMBER;
      hash = (53 * hash) + getTarekomisList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yt8492.evileye.protobuf.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yt8492.evileye.protobuf.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yt8492.evileye.protobuf.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code evileye.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:evileye.User)
      com.yt8492.evileye.protobuf.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yt8492.evileye.protobuf.User.class, com.yt8492.evileye.protobuf.User.Builder.class);
    }

    // Construct using com.yt8492.evileye.protobuf.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTarekomisFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      userName_ = "";

      if (tarekomisBuilder_ == null) {
        tarekomis_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        tarekomisBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yt8492.evileye.protobuf.EeProto.internal_static_evileye_User_descriptor;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.User getDefaultInstanceForType() {
      return com.yt8492.evileye.protobuf.User.getDefaultInstance();
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.User build() {
      com.yt8492.evileye.protobuf.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yt8492.evileye.protobuf.User buildPartial() {
      com.yt8492.evileye.protobuf.User result = new com.yt8492.evileye.protobuf.User(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.userId_ = userId_;
      result.userName_ = userName_;
      if (tarekomisBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tarekomis_ = java.util.Collections.unmodifiableList(tarekomis_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tarekomis_ = tarekomis_;
      } else {
        result.tarekomis_ = tarekomisBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yt8492.evileye.protobuf.User) {
        return mergeFrom((com.yt8492.evileye.protobuf.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yt8492.evileye.protobuf.User other) {
      if (other == com.yt8492.evileye.protobuf.User.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (tarekomisBuilder_ == null) {
        if (!other.tarekomis_.isEmpty()) {
          if (tarekomis_.isEmpty()) {
            tarekomis_ = other.tarekomis_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTarekomisIsMutable();
            tarekomis_.addAll(other.tarekomis_);
          }
          onChanged();
        }
      } else {
        if (!other.tarekomis_.isEmpty()) {
          if (tarekomisBuilder_.isEmpty()) {
            tarekomisBuilder_.dispose();
            tarekomisBuilder_ = null;
            tarekomis_ = other.tarekomis_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tarekomisBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTarekomisFieldBuilder() : null;
          } else {
            tarekomisBuilder_.addAllMessages(other.tarekomis_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yt8492.evileye.protobuf.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yt8492.evileye.protobuf.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 1;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string user_name = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_name = 2;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string user_name = 2;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.yt8492.evileye.protobuf.Tarekomi> tarekomis_ =
      java.util.Collections.emptyList();
    private void ensureTarekomisIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        tarekomis_ = new java.util.ArrayList<com.yt8492.evileye.protobuf.Tarekomi>(tarekomis_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yt8492.evileye.protobuf.Tarekomi, com.yt8492.evileye.protobuf.Tarekomi.Builder, com.yt8492.evileye.protobuf.TarekomiOrBuilder> tarekomisBuilder_;

    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public java.util.List<com.yt8492.evileye.protobuf.Tarekomi> getTarekomisList() {
      if (tarekomisBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tarekomis_);
      } else {
        return tarekomisBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public int getTarekomisCount() {
      if (tarekomisBuilder_ == null) {
        return tarekomis_.size();
      } else {
        return tarekomisBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public com.yt8492.evileye.protobuf.Tarekomi getTarekomis(int index) {
      if (tarekomisBuilder_ == null) {
        return tarekomis_.get(index);
      } else {
        return tarekomisBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder setTarekomis(
        int index, com.yt8492.evileye.protobuf.Tarekomi value) {
      if (tarekomisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTarekomisIsMutable();
        tarekomis_.set(index, value);
        onChanged();
      } else {
        tarekomisBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder setTarekomis(
        int index, com.yt8492.evileye.protobuf.Tarekomi.Builder builderForValue) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.set(index, builderForValue.build());
        onChanged();
      } else {
        tarekomisBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder addTarekomis(com.yt8492.evileye.protobuf.Tarekomi value) {
      if (tarekomisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTarekomisIsMutable();
        tarekomis_.add(value);
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder addTarekomis(
        int index, com.yt8492.evileye.protobuf.Tarekomi value) {
      if (tarekomisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTarekomisIsMutable();
        tarekomis_.add(index, value);
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder addTarekomis(
        com.yt8492.evileye.protobuf.Tarekomi.Builder builderForValue) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.add(builderForValue.build());
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder addTarekomis(
        int index, com.yt8492.evileye.protobuf.Tarekomi.Builder builderForValue) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.add(index, builderForValue.build());
        onChanged();
      } else {
        tarekomisBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder addAllTarekomis(
        java.lang.Iterable<? extends com.yt8492.evileye.protobuf.Tarekomi> values) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tarekomis_);
        onChanged();
      } else {
        tarekomisBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder clearTarekomis() {
      if (tarekomisBuilder_ == null) {
        tarekomis_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tarekomisBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public Builder removeTarekomis(int index) {
      if (tarekomisBuilder_ == null) {
        ensureTarekomisIsMutable();
        tarekomis_.remove(index);
        onChanged();
      } else {
        tarekomisBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public com.yt8492.evileye.protobuf.Tarekomi.Builder getTarekomisBuilder(
        int index) {
      return getTarekomisFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomisOrBuilder(
        int index) {
      if (tarekomisBuilder_ == null) {
        return tarekomis_.get(index);  } else {
        return tarekomisBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public java.util.List<? extends com.yt8492.evileye.protobuf.TarekomiOrBuilder> 
         getTarekomisOrBuilderList() {
      if (tarekomisBuilder_ != null) {
        return tarekomisBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tarekomis_);
      }
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public com.yt8492.evileye.protobuf.Tarekomi.Builder addTarekomisBuilder() {
      return getTarekomisFieldBuilder().addBuilder(
          com.yt8492.evileye.protobuf.Tarekomi.getDefaultInstance());
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public com.yt8492.evileye.protobuf.Tarekomi.Builder addTarekomisBuilder(
        int index) {
      return getTarekomisFieldBuilder().addBuilder(
          index, com.yt8492.evileye.protobuf.Tarekomi.getDefaultInstance());
    }
    /**
     * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
     */
    public java.util.List<com.yt8492.evileye.protobuf.Tarekomi.Builder> 
         getTarekomisBuilderList() {
      return getTarekomisFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yt8492.evileye.protobuf.Tarekomi, com.yt8492.evileye.protobuf.Tarekomi.Builder, com.yt8492.evileye.protobuf.TarekomiOrBuilder> 
        getTarekomisFieldBuilder() {
      if (tarekomisBuilder_ == null) {
        tarekomisBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yt8492.evileye.protobuf.Tarekomi, com.yt8492.evileye.protobuf.Tarekomi.Builder, com.yt8492.evileye.protobuf.TarekomiOrBuilder>(
                tarekomis_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        tarekomis_ = null;
      }
      return tarekomisBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:evileye.User)
  }

  // @@protoc_insertion_point(class_scope:evileye.User)
  private static final com.yt8492.evileye.protobuf.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yt8492.evileye.protobuf.User();
  }

  public static com.yt8492.evileye.protobuf.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yt8492.evileye.protobuf.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

