// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   */
  long getUserId();

  /**
   * <code>string user_name = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  java.util.List<com.yt8492.evileye.protobuf.Tarekomi> 
      getTarekomisList();
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  com.yt8492.evileye.protobuf.Tarekomi getTarekomis(int index);
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  int getTarekomisCount();
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  java.util.List<? extends com.yt8492.evileye.protobuf.TarekomiOrBuilder> 
      getTarekomisOrBuilderList();
  /**
   * <code>repeated .evileye.Tarekomi tarekomis = 3;</code>
   */
  com.yt8492.evileye.protobuf.TarekomiOrBuilder getTarekomisOrBuilder(
      int index);
}
