// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface UsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.Users)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .evileye.User users = 1;</code>
   */
  java.util.List<com.yt8492.evileye.protobuf.User> 
      getUsersList();
  /**
   * <code>repeated .evileye.User users = 1;</code>
   */
  com.yt8492.evileye.protobuf.User getUsers(int index);
  /**
   * <code>repeated .evileye.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .evileye.User users = 1;</code>
   */
  java.util.List<? extends com.yt8492.evileye.protobuf.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .evileye.User users = 1;</code>
   */
  com.yt8492.evileye.protobuf.UserOrBuilder getUsersOrBuilder(
      int index);
}
