// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/api.proto

package com.yt8492.evileye.protobuf;

public interface VoteReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:evileye.VoteReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tarekomi_id = 1;</code>
   */
  long getTarekomiId();

  /**
   * <code>string desc = 2;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
